name: "npm build app"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      env:
        CI: false
      run: |
        npm install
        npm run build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: build_files
        path: ./build
        compression-level: 0
        overwrite: true
    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: AKIAVIJGNWVSO7SPPZGB
        aws_secret_access_key: 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
        aws_bucket: gyrocar-static-files
        source_dir: 'build'
